### ISSUE TITLE
Model generated with property Map<String, Decimal> failed compilation 

### ISSUE THREAD

**Issue by alqh** [ClearPointNZ/connect-java#28]
I am attempting to define a schema that has a property of Map<String, BigDecimal>. To achieve that, I defined it as follows:

```
MyModel:
  properties:
    id:
      type: string
    my_items:
      type: object
      additionalProperties:
        type: number
        format: decimal
```
[Open Api schema for defining map](https://swagger.io/docs/specification/data-models/dictionaries/)

This output the Model, but the compilation fails on the copy method. This is because the it is trying to invoke copy() on the value of the Map, which in this case, is a BigDecimal
```
public class ModelDto {
  @JsonProperty("my_items")
  private Map<String, BigDecimal> myItems = new HashMap<>();
   public ModelDto copy() {
    ModelDto copy = new ModelDto();
// ... some code
 this.getMyItems().entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey, t -> t.getValue().copy())));

    return copy;
  }
}
```

From the [POJO template](https://github.com/ClearPointNZ/connect-java/blob/master/maven-plugins/openapi-jersey2-plugin/src/main/resources/jersey2-v3template/pojo.mustache#L243-L248), it looks like it is driven off the `isPrimitive` flag, but looks like BigDecimal is not considered primitive. Is there some way we can handle BigDecimal. Also, I notice that there is a `isModel` flag, is it relevant in this case ? 

I'm currently using :
*  id 'org.openapi.generator' version '5.0.0-beta2'
*"cd.connect.openapi:connect-openapi-jersey2:5.4"

**Comment by alqh** [comment]
As per discussion, I pulled the branch you mentioned where you added the following:

```
AddProps3:
      properties:
        discrim:
          type: string
        readings:
          type: object
          additionalProperties:
            type: number
            format: decimal
```

Under 5.0.0 openapi-generator, there isn't error on copy because it didn't try to copy the map:
```
public AddProps3 copy() {
    AddProps3 copy = new AddProps3();

    copy.setDiscrim(this.getDiscrim());

    return copy;
  }
```

Under 5.0.0-beta openapi-generator, it errors, and seem like the copy method has way more stuff:
```
 public AddProps3 copy() {
    AddProps3 copy = new AddProps3();

    copy.setDiscrim(this.getDiscrim());
    copy.setReadings(this.getReadings() == null ? null : this.getReadings().entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey, t -> t.getValue().copy())));
    copy.setExtra(this.getExtra() == null ? null : this.getExtra().entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey, t -> t.getValue().copy())));
    copy.setDependencies(this.getDependencies() == null ? null : this.getDependencies().entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey, t -> t.getValue().copy())));
    copy.setOtherDeps(this.getOtherDeps() == null ? null : this.getOtherDeps().entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue)));
    copy.setYetMoreAdditional(this.getYetMoreAdditional() == null ? null : this.getYetMoreAdditional().entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey, t -> t.getValue().copy())));
    copy.setMapWithComplexObject(this.getMapWithComplexObject() == null ? null : this.getMapWithComplexObject().entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey, t -> t.getValue().copy())));
    copy.setMapWithEnums(this.getMapWithEnums() == null ? null : this.getMapWithEnums().entrySet().stream().collect(java.util.stream.Collectors.toMap(Map.Entry::getKey, t -> t.getValue().copy())));

    return copy;
  }
```

**Comment by alqh** [comment]
Looks like declaring it as number with format "decimal" produces the following warning 
```
Unknown `format` decimal detected for type `number`. Defaulting to `number`
```

Having a look at the code here, the typemapping of "number" already maps to BigDecimal, so probably no need for the formatting. The warning is at line 2048 [See DefaultCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L2049)

But the changes for the `isModel` works good

**Comment by alqh** [comment]
It is still not compatible for 5.0.0 for case where there are query parameters:


Generated (no commas between the parameters):
```
/**
    * 
    * 
      * @param searchParamOne  (required)
      * @param searchParamTwo  (optional)
      * @return List&lt;TestDTO&gt;
    */
    @GET
    @Produces({ "application/json" })
    
    public List<TestDTO> search( @NotNull  @QueryParam("search_param_one") UUID searchParamOne  @QueryParam("search_param_two") String searchParamTwo);
```

Here are the changes I've made [See forked comparison](https://github.com/ClearPointNZ/connect-java/compare/angeline...alqh:angeline)

**Comment by rvowles** [comment]
#hasMore -> ^-last - i'm fixing it now

**Comment by alqh** [comment]
Cool, please let me know when you do have one, I can give the JAR a whirl . Thank you @rvowles for helping on this issue

**Comment by rvowles** [comment]
I did push the changes that should have fixed the issues you have been seeing. Unfortunately for me I have a remaining one that I'm planning on fixing this morning.

**Comment by alqh** [comment]
I applied the JAR for my project and had a look at the diff of classes generated. Looks good. Just a quick question regarding the bottom scenario. The generated code is correct, I'm just wondering if it was intended that the path `/heartbeat` is attached to the classes's root rather than the method. 

![image](https://user-images.githubusercontent.com/1378494/104358155-eca80880-5572-11eb-8184-fb8dd1ead232.png)

LGTM.

**Comment by rvowles** [comment]
Yes - its a feature of OpenAPI v5, it is walking through the methods in your declaration and finding their common root and putting it in the base @Path annotation. This is what tripped me up because that doesn't work sometimes.
